# Generated by Django 4.1 on 2025-04-18 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0002_auto_20250418_0958"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activity",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="leaderboard",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="workout",
            old_name="_id",
            new_name="id",
        ),
    ]
